namespace DotnetAcademy.CliBasicsDemo;

public static class CliBasicsPresenter
{
    public static IReadOnlyList<string> BuildLines()
    {
        return BuildLines(Environment.Version);
    }

    public static IReadOnlyList<string> BuildLines(Version runtimeVersion)
    {
        const string title = "Dotnet Academy: Development Environment And CLI";

        return new[]
        {
            title,
            new string('-', title.Length),
            $"Runtime version from the running app: {runtimeVersion}",
            "Use `dotnet --version` in the terminal to inspect the installed SDK version.",
            string.Empty,
            "Core files and folders in this sample:",
            "- Program.cs contains the application code.",
            "- DotnetAcademy.CliBasicsDemo.csproj defines project settings.",
            "- bin/ and obj/ are generated by the build process.",
            string.Empty,
            "Next commands to practice:",
            "dotnet build",
            "dotnet run",
            "dotnet --info"
        };
    }
}
